### ISSUE TITLE
Question: Custom Icon?

### ISSUE THREAD

**Issue by Mattin** [api-platform/admin#127]
Hello,

is it possible to use custom icon on resource? Thanks.

**Comment by Olcina** [comment]
Hi, I have the same issue, I would like to change the icon for the resource.

Looking at `resourceFactory.js`  the resource definition from `react-admin` in the api-platform admin looks as follows 

```
<Resource
      {...props}
      create={create}
      edit={edit}
      key={name}
      list={list}
      name={name}
      options={{
        api,
        fieldFactory,
        inputFactory,
        parameterFactory,
        resource,
      }}
      show={show}
    />
```

Looking at the react-admin doc in the [resource](https://github.com/marmelab/react-admin/blob/master/docs/Resource.md) page. I think that it can be included just adding the icon props to the resourceFactory so that it can latter added to the API resources and send it to <AdminBuilder />

Will try to work on this if I have the time.

**Comment by Olcina** [comment]
Hi @Mattin This issue can be closed.

**Comment by Mattin** [comment]
Great! Thank you @Olcina 👍
