### ISSUE TITLE
FEATURE: Parse Hydra supportedOperations to disable/enable Buttons

### ISSUE THREAD

**Issue by playmice** [api-platform/admin#44]
Parse collectionOperations and itemOperations to disable/enable CREATE/DELETE/EDIT Buttons.
docs.jsonld currently returns supported itemOperations and collectionOperations for each resource. parseHydraDocumentation should be extended to parse these operations, and HydraAdmin should use this to determine which buttons to enable. 
If, for example, DELETE itemOperation is disabled on a resource, then the DELETE button should not appear on the edit form. If PUT is disabled, then EDIT button should not appear. 
I believe you get the idea.

**Comment by mauchede** [comment]
Since [PR-63](https://github.com/api-platform/admin/pull/63), you have the possibility to customize CRUD components. By default, all actions are enabled. If you wish to disable a component, you just have to define its value to `null`.

For example:

```js
const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint)
  .then(api => {
    api.resources.map(resource => {
      const books = api.resources.find(r => 'books' === r.name);
      books.create = null; // disable "create" button and view
      books.edit = null; // disable "edit" button and view
      books.remove = null; // disable "delete" button
      books.show = null; // disable "show" button and view

      return resource;
    });

    return api;
  })
;
```

I will open a PR on `api-platform/docs` to explain how we can customize theses behaviors.
