### ISSUE TITLE
dont show Logout button

### ISSUE THREAD

**Issue by ViPErCZ** [api-platform/admin#549]
When updating to "@api-platform/admin": "^3.4.6" the logout button does not appear. When I'm not logged in, the login page doesn't even show up. The URL goes to the first result and an error appears (because I'm not logged in). Version 3.4.5 is fine.

**Comment by AmanAzim** [comment]
I having the same issue I had to rollback to `3.4.5` but with this old version backend errors are not shown anymore, all the errors appears as "Server communication error".
I am adding screen shots below of the missing logout/ login option with the version `@api-platform/admin": "^3.4.6"`.  Also it is causing authentication failure. After the auth token gets expired instead of redirecting to the login page it shows empty resource page. Cannot react the login page even by manually inserting the `/#/login` url in the browser
<img width="1692" alt="Screenshot 2024-04-22 at 19 03 10" src="https://github.com/api-platform/admin/assets/46650894/cf56842f-7dcf-4654-a7c7-7686dfadb942">

**Comment by PawelSuwinski** [comment]
3.4.6 does not pass auth provider to AdminContext (will be restored in 3.4.7), however returning to contex wrapping Admin component  should fix it:

```
<HydraAdmin 
  admin={Admin}
  //...
```

**Comment by ViPErCZ** [comment]
Ok, thanks. This solution works. ;-)
