### ISSUE TITLE
Using Custom Components doesn't work

### ISSUE THREAD

**Issue by mamoot64** [api-platform/admin#70]
Hi,

I try to add a "RichTextField" & "RichTextInput" on a "description" field.
I follow the guide from doc. It's seems that tutorial is outdated.

Here is the new code (fixed new import, fixed key to access resources, minors refactors) : 

```javascript
import React from 'react';
import { RichTextField } from 'admin-on-rest';
import RichTextInput from 'aor-rich-text-input';
import { HydraAdmin } from '@api-platform/admin';
import parseHydraDocumentation from '@api-platform/api-doc-parser/lib/hydra/parseHydraDocumentation';

const entrypoint = 'https://demo.api-platform.com';

const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint)
 .then(parsedApi => {

  parsedApi.api.resources.map(resource => {

   if ('books' === resource.name) {
    resource.fields.find(f => 'description' === f.name).fieldComponent = <RichTextField source="description" key="description" /> ;
    resource.fields.find(f => 'description' === f.name).inputComponent = <RichTextInput source="description" key="description" /> ;
   }

   return resource;
  });

  return parsedApi;
 });

export default () => <HydraAdmin apiDocumentationParser={apiDocumentationParser} entrypoint={entrypoint} />;
```
The RichTextInput is installed : 
````
yarn add aor-rich-text-input
````

With this configuration, the RichTextInput & RichTextField are not displayed on admin.
If I inspect the element with a ```console.log('PARSED API', parsedApi); ``` on the "apiDocumentationParser" function, the field type is correct (Type : RichTextInput).

What I have missed ?

When it's fixed for me, I'll make a PR to update doc.

Thank's for your help.

Nico

**Comment by acidline** [comment]
Ok, the problem seems to be the same to this : [Documentation on api-doc-parser incorrect](https://github.com/api-platform/docs/issues/332)

Some changes are made for a better customization such as describe here : [Customize CRUD components](https://github.com/api-platform/admin/pull/63)

Here is my new code : 

myEntryPoint.js

``` javascript
import parseHydraDocumentation from '@api-platform/api-doc-parser/lib/hydra/parseHydraDocumentation';
import React from 'react';

import { RichTextField } from 'admin-on-rest';
import RichTextInput from 'aor-rich-text-input';

export default entrypoint => parseHydraDocumentation(entrypoint)
  .then( ({ api }) => {

    const books = api.resources.find(({ name }) => 'books ' === name);

    const description = books.fields.find(f => 'description' === f.name);
    description.field = props => (
        <RichTextField {...props} source="description" />
    );
    description.input = props =>  (
        <RichTextInput {...props} source="description" />
     );
    return { api };
  })
;
```

How to use the exported "entrypoint " in App.js ?

App.js

``` javascript
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';

import entrypoint from './myEntryPoint'; // ???

const apiUrl = 'http://localhost:8000';

export default () => <HydraAdmin entrypoint={apiUrl} />;
```

Nico le Noob

**Comment by acidline** [comment]
Ok, I'm working slowly...

Here is my state : 

App.js

```javascript
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';
import myEntryPoint from './myEntryPoint';

const apiUrl = 'http://localhost:8000';

export default () => <HydraAdmin apiDocumentationParser={myEntryPoint} entrypoint={apiUrl} />;
```
With this parser, the **RichTextField works great**.
**The RichTextInput not**. 

I follow my investigations.

Helps are welcome !!! ;)

**Comment by mauchede** [comment]
Hi @acidline,

Thank you for your patience.

As said in [your PR on api-platform/docs](https://github.com/api-platform/docs/pull/343), to enable the property injection, you have to define `addField` in the context of `input`. For your example, you have to define something like this:

```js
description.input.defaultProps = {
    addLabel: true,
    addField: true,
};
```

This behavior is due to [admin-on-rest/FormField](https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/src/mui/form/FormField.js#L35).
